import manifest from '@/public/images/manifest.json'

// Variants are generated by scripts/optimize-images.mjs; the manifest lists their dimensions.
export type ImageKey = keyof typeof manifest

const MIME: Record<string, string> = { avif: 'image/avif', webp: 'image/webp', png: 'image/png' }

function srcSet(key: ImageKey, format: string) {
  return manifest[key].variants.map((v) => `/images/${key}/${v.width}.${format} ${v.width}w`).join(', ')
}

function largest(key: ImageKey) {
  return manifest[key].variants[manifest[key].variants.length - 1]
}

type ArtDirection = { image: ImageKey; media: string; sizes: string }

type PictureProps = {
  image: ImageKey
  alt: string
  sizes: string
  className?: string
  /** Above-the-fold LCP image only: eager loading with high fetch priority. */
  priority?: boolean
  /** Overrides the default lazy loading for other above-the-fold images (e.g. the navbar logo). */
  loading?: 'lazy' | 'eager'
  /** Alternative crops, tried in order before the default image. */
  artDirection?: ArtDirection[]
}

export function Picture({ image, alt, sizes, className, priority = false, loading, artDirection = [] }: PictureProps) {
  const { formats, variants } = manifest[image]
  const fallback = formats[formats.length - 1]
  const { width, height } = largest(image)

  return (
    <picture>
      {artDirection.flatMap((art) =>
        manifest[art.image].formats.map((format) => (
          <source
            key={`${art.image}-${format}`}
            media={art.media}
            type={MIME[format]}
            srcSet={srcSet(art.image, format)}
            sizes={art.sizes}
            width={largest(art.image).width}
            height={largest(art.image).height}
          />
        )),
      )}
      {formats.map((format) => (
        <source key={format} type={MIME[format]} srcSet={srcSet(image, format)} sizes={sizes} />
      ))}
      <img
        src={`/images/${image}/${variants[Math.min(1, variants.length - 1)].width}.${fallback}`}
        srcSet={srcSet(image, fallback)}
        sizes={sizes}
        width={width}
        height={height}
        alt={alt}
        className={className}
        loading={priority ? 'eager' : (loading ?? 'lazy')}
        decoding="async"
        fetchPriority={priority ? 'high' : undefined}
      />
    </picture>
  )
}
